END_OF_TURN = -1
DRAW_A_CARD = -2
START_YOUR_TURN = -4
END_OF_PLAYING = -3
YOU_LOSE = -10
SOMEONE_LOSES = -12

#Card ID
CARD_BOMB = 0
CARD_DEFUSE = 1
CARD_ATTACK = 2
CARD_TARGETED_ATTACK = 3
CARD_SKIP = 4
CARD_NOPE = 5
CARD_FAVOR = 6
CARD_SHUFFLE = 7
CARD_SEE_THE_FUTURE = 8
CARD_USELESS_CAT_1 = 9
CARD_USELESS_CAT_2 = 10
CARD_USELESS_CAT_3 = 11
CARD_USELESS_CAT_4 = 12
CARD_USELESS_CAT_5 = 13

#CONSTANT QUANTITY
SEE_THE_FUTURE_NUM = 3