END_OF_TURN = -1
DRAW_A_CARD = -2
START_YOUR_TURN = -4
END_YOUR_TURN = -105
YOU_LOSE = -10
SOMEONE_LOSES = -12
ASK_RESPONSE = -100
DEAL_CARDS = -101
DECK_SHUFFLED = -102
NO_RESPONSE = -103
START_NEW_PLAY = -104

#Card ID
CARD_BOMB = 0
CARD_DEFUSE = 1
CARD_ATTACK = 2
CARD_TARGETED_ATTACK = 3
CARD_SKIP = 4
CARD_NOPE = 5
CARD_FAVOR = 6
CARD_SHUFFLE = 7
CARD_SEE_THE_FUTURE = 8
CARD_USELESS_CAT_1 = 9
CARD_USELESS_CAT_2 = 10
CARD_USELESS_CAT_3 = 11
CARD_USELESS_CAT_4 = 12
CARD_USELESS_CAT_5 = 13

#CONSTANT QUANTITY
SEE_THE_FUTURE_NUM = 3
START_HAND = 5
ATTACK_POWER = 2